name: Digest Auto Update

on:
  workflow_dispatch: # 수동 실행을 위한 트리거
  push:              # <<< 이 부분을 추가합니다.
    branches:
      - main         # main 브랜치에 푸시될 때마다 워크플로우 실행을 트리거합니다.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PyMuPDF openai

      - name: Run pipeline
        run: python scripts/stock_digest_pipeline.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add public/digests
          git commit -m 'Auto update digest' || echo 'No changes'
          git push

      - name: Upload pages artifact 
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
